### ISSUE TITLE
Suggestion: mention the new `SetLimit` function found in the golang.org/x/sync `errgroup` package in README.md

### ISSUE THREAD

**Issue by narsimhamchelluri-ds** [neilotoole/errgroupn#14]
It looks like the `sync/errgroup` package now has a `SetLimit` function. You can see the documentation at https://pkg.go.dev/golang.org/x/sync/errgroup#Group.SetLimit . I believe that [this is a fairly recent happening](https://cs.opensource.google/go/x/sync/+/0976fa681c295de5355f7a4d968b56cb9da8a76b).

I feel like a mention of this new function in the original package in the `README.md` is probably merited.

There is some difference in the two APIs of the two packages; this one has a `WithContextN(ctx, numG, qSize)` function whereas that one has just `WithContext(ctx)` and `SetLimit(n)` functions. At a glance it seems like the `n` in the original pretty similar to the `numG` parameter here, and there doesn't seem to be a `qSize` parameter in the original package. I definitely have not compared the two packages in detail, or really even attempted to understand the implementation of either one. I am just an end-user.

I used this package some time ago at a previous job (maybe two of them, actually, I can't quite remember) and it was helpful for my purposes, so thank you for that. Ultimately, I'm wondering now if using this package in new code is necessary or recommended, given the new `SetLimit` function in the original package, and would appreciate hearing any thoughts from more knowledgeable sources.

**Comment by neilotoole** [comment]
Done.
